security:
    # comment le mot de passe est encrypté
    encoders:
        App\Entity\User:
            #argon2i par défaut
            algorithm: argon2i

    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
        database:
            entity:
                #les utilisateurs viennent de l'entité User
                #et l'identifiant est le pseudo
                class: App\Entity\User
                property: pseudo
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: lazy
            provider: database

            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#firewalls-authentication

            # route du formulaire de login
            form_login:
                login_path: app_user_login #où se trouve le formulaire
                check_path: app_user_login #où se font les traitements (équivalent de action dans la balise form)
            # route de la page de déconnexion
            logout:
                path: app_user_logout

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
         - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }
